### ISSUE TITLE
BAD signature

### ISSUE THREAD

**Issue by mohammadrashidi** [HariantoAtWork/docker-xnmp-vhosts#1]
Hi

While installation, I got these logs and installation interrupt.

Summery:

docker-compose up
Building 8-0-0-fpm-ext
Step 1/6 : FROM php:8.0.0-fpm-alpine
 ---> 924778312b98
Step 2/6 : RUN curl -s https://getcomposer.org/installer | php   && mv composer.phar /usr/local/bin/composer   && composer about
 ---> Using cache
 ---> d1d206c13806
Step 3/6 : RUN php -m && echo "============================================="
 ---> Using cache
 ---> 66c364111245
Step 4/6 : RUN apk add --no-cache --update   bzip2-dev   enchant2-dev   libpng-dev   gmp-dev   imap-dev   icu-dev   openldap-dev   freetds-dev   postgresql-dev   aspell-dev   net-snmp-dev   libxml2-dev   tidyhtml-dev    libxslt-dev   libzip-dev
 ---> Running in cd20d6433603
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/95) Installing libintl (0.20.2-r0)
(2/95) Installing libgcc (9.3.0-r2)
(3/95) Installing libstdc++ (9.3.0-r2)
(4/95) Installing aspell-libs (0.60.8-r0)
(5/95) Installing aspell (0.60.8-r0)
(6/95) Installing libbz2 (1.0.8-r1)
(7/95) Installing perl (5.30.3-r0)
ERROR: Failed to create usr/lib/perl5/core_perl/auto/Encode/CN/CN.so: No error information
ERROR: perl-5.30.3-r0: BAD signature
(8/95) Installing aspell-utils (0.60.8-r0)
(9/95) Installing aspell-dev (0.60.8-r0)
(10/95) Installing bzip2-dev (1.0.8-r1)
(11/95) Installing libffi (3.3-r2)
(12/95) Installing libblkid (2.35.2-r0)
(13/95) Installing libmount (2.35.2-r0)
(14/95) Installing pcre (8.44-r0)
(15/95) Installing glib (2.64.6-r0)
(16/95) Installing icu-libs (67.1-r0)
ERROR: Failed to create usr/lib/libicudata.so.67.1: No error information
ERROR: icu-libs-67.1-r0: BAD signature
(17/95) Installing boost-locale (1.72.0-r6)
(18/95) Installing nuspell (3.1.1-r0)
(19/95) Installing enchant2 (2.2.8-r2)
(20/95) Installing expat (2.2.9-r1)
(21/95) Installing gdbm (1.13-r1)
(22/95) Installing readline (8.0.4-r0)
(23/95) Installing python3 (3.8.5-r0)
(24/95) Installing gettext-asprintf (0.20.2-r0)
(25/95) Installing libunistring (0.9.10-r0)
(26/95) Installing gettext-libs (0.20.2-r0)
(27/95) Installing libgomp (9.3.0-r2)
(28/95) Installing gettext (0.20.2-r0)
(29/95) Installing gettext-dev (0.20.2-r0)
(30/95) Installing libxml2-utils (2.9.10-r5)
(31/95) Installing libgpg-error (1.37-r0)
(32/95) Installing libgcrypt (1.8.5-r0)
(33/95) Installing libxslt (1.1.34-r0)
(34/95) Installing docbook-xml (4.5-r6)
Executing docbook-xml-4.5-r6.post-install
(35/95) Installing docbook-xsl (1.79.2-r2)
Executing docbook-xsl-1.79.2-r2.post-install
(36/95) Installing linux-headers (5.4.5-r1)
(37/95) Installing pkgconf (1.7.2-r0)
(38/95) Installing libffi-dev (3.3-r2)
(39/95) Installing libpcre16 (8.44-r0)
(40/95) Installing libpcre32 (8.44-r0)
(41/95) Installing libpcrecpp (8.44-r0)
(42/95) Installing pcre-dev (8.44-r0)
(43/95) Installing blkid (2.35.2-r0)
(44/95) Installing libcap-ng (0.7.10-r1)
(45/95) Installing setpriv (2.35.2-r0)
(46/95) Installing libsmartcols (2.35.2-r0)
(47/95) Installing findmnt (2.35.2-r0)
(48/95) Installing mcookie (2.35.2-r0)
(49/95) Installing hexdump (2.35.2-r0)
(50/95) Installing lsblk (2.35.2-r0)
(51/95) Installing libuuid (2.35.2-r0)
(52/95) Installing libfdisk (2.35.2-r0)
(53/95) Installing sfdisk (2.35.2-r0)
(54/95) Installing cfdisk (2.35.2-r0)
(55/95) Installing util-linux (2.35.2-r0)
(56/95) Installing util-linux-dev (2.35.2-r0)
(57/95) Installing zlib-dev (1.2.11-r3)
(58/95) Installing glib-dev (2.64.6-r0)
(59/95) Installing enchant2-dev (2.2.8-r2)
(60/95) Installing unixodbc (2.3.7-r2)
(61/95) Installing freetds (1.1.40-r0)
(62/95) Installing freetds-dev (1.1.40-r0)
(63/95) Installing gmp (6.2.0-r0)
(64/95) Installing libgmpxx (6.2.0-r0)
(65/95) Installing gmp-dev (6.2.0-r0)
(66/95) Installing icu (67.1-r0)
(67/95) Installing icu-dev (67.1-r0)
(68/95) Installing c-client (2007f-r11)
(69/95) Installing imap-dev (2007f-r11)
(70/95) Installing libpng (1.6.37-r1)
(71/95) Installing libpng-dev (1.6.37-r1)
(72/95) Installing xz-dev (5.2.5-r0)
(73/95) Installing libxml2-dev (2.9.10-r5)
(74/95) Installing libxslt-dev (1.1.34-r0)
(75/95) Installing libzip (1.6.1-r1)
(76/95) Installing libzip-dev (1.6.1-r1)
(77/95) Installing openssl-dev (1.1.1i-r0)
(78/95) Installing net-snmp-libs (5.8-r3)
(79/95) Installing net-snmp-agent-libs (5.8-r3)
(80/95) Installing net-snmp-dev (5.8-r3)
ERROR: Failed to create usr/lib/libnetsnmpmibs.a: No error information
ERROR: net-snmp-dev-5.8-r3: BAD signature
(81/95) Installing db (5.3.28-r1)
(82/95) Installing libsasl (2.1.27-r6)
(83/95) Installing cyrus-sasl-dev (2.1.27-r6)
(84/95) Installing libldap (2.4.50-r1)
(85/95) Installing libldapcpp (2.4.50-r1)
(86/95) Installing openldap-dev (2.4.50-r1)
(87/95) Installing llvm10-libs (10.0.0-r2)
ERROR: Failed to create usr/lib/libLLVM-10.so: No error information
ERROR: llvm10-libs-10.0.0-r2: BAD signature
(88/95) Installing clang-libs (10.0.0-r2)
ERROR: Failed to create usr/lib/libclang-cpp.so.10: No error information
ERROR: clang-libs-10.0.0-r2: BAD signature
(89/95) Installing clang (10.0.0-r2)
ERROR: Failed to create usr/bin/c-index-test: No error information
ERROR: clang-10.0.0-r2: BAD signature
(90/95) Installing llvm10 (10.0.0-r2)
(91/95) Installing libpq (12.5-r0)
(92/95) Installing postgresql-libs (12.5-r0)
(93/95) Installing postgresql-dev (12.5-r0)
(94/95) Installing tidyhtml-libs (5.6.0-r0)
(95/95) Installing tidyhtml-dev (5.6.0-r0)
Executing busybox-1.31.1-r19.trigger
Executing glib-2.64.6-r0.trigger
No schema files found: doing nothing.
6 errors; 166 MiB in 120 packages
ERROR: Service '8-0-0-fpm-ext' failed to build : The command '/bin/sh -c apk add --no-cache --update   bzip2-dev   enchant2-dev   libpng-dev   gmp-dev   imap-dev   icu-dev   openldap-dev   freetds-dev   postgresql-dev   aspell-dev   net-snmp-dev   libxml2-dev   tidyhtml-dev    libxslt-dev   libzip-dev' returned a non-zero code: 6

Regards,
Mohammad

**Comment by HariantoAtWork** [comment]
I'll try to delete this image and check what’s going on.

**Comment by HariantoAtWork** [comment]
> Hi
> 
> While installation, I got these logs and installation interrupt.
> 
> Summery:
> 
> docker-compose up
> Building 8-0-0-fpm-ext
> Step 1/6 : FROM php:8.0.0-fpm-alpine
> ---> 924778312b98
> Step 2/6 : RUN curl -s https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && composer about
> ---> Using cache
> ---> d1d206c13806
> Step 3/6 : RUN php -m && echo "============================================="
> ---> Using cache
> ---> 66c364111245
> Step 4/6 : RUN apk add --no-cache --update bzip2-dev enchant2-dev libpng-dev gmp-dev imap-dev icu-dev openldap-dev freetds-dev postgresql-dev aspell-dev net-snmp-dev libxml2-dev tidyhtml-dev libxslt-dev libzip-dev
> ---> Running in cd20d6433603
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
> (1/95) Installing libintl (0.20.2-r0)
> (2/95) Installing libgcc (9.3.0-r2)
> (3/95) Installing libstdc++ (9.3.0-r2)
> (4/95) Installing aspell-libs (0.60.8-r0)
> (5/95) Installing aspell (0.60.8-r0)
> (6/95) Installing libbz2 (1.0.8-r1)
> (7/95) Installing perl (5.30.3-r0)
> ERROR: Failed to create usr/lib/perl5/core_perl/auto/Encode/CN/CN.so: No error information
> ERROR: perl-5.30.3-r0: BAD signature
> (8/95) Installing aspell-utils (0.60.8-r0)
> (9/95) Installing aspell-dev (0.60.8-r0)
> (10/95) Installing bzip2-dev (1.0.8-r1)
> (11/95) Installing libffi (3.3-r2)
> (12/95) Installing libblkid (2.35.2-r0)
> (13/95) Installing libmount (2.35.2-r0)
> (14/95) Installing pcre (8.44-r0)
> (15/95) Installing glib (2.64.6-r0)
> (16/95) Installing icu-libs (67.1-r0)
> ERROR: Failed to create usr/lib/libicudata.so.67.1: No error information
> ERROR: icu-libs-67.1-r0: BAD signature
> (17/95) Installing boost-locale (1.72.0-r6)
> (18/95) Installing nuspell (3.1.1-r0)
> (19/95) Installing enchant2 (2.2.8-r2)
> (20/95) Installing expat (2.2.9-r1)
> (21/95) Installing gdbm (1.13-r1)
> (22/95) Installing readline (8.0.4-r0)
> (23/95) Installing python3 (3.8.5-r0)
> (24/95) Installing gettext-asprintf (0.20.2-r0)
> (25/95) Installing libunistring (0.9.10-r0)
> (26/95) Installing gettext-libs (0.20.2-r0)
> (27/95) Installing libgomp (9.3.0-r2)
> (28/95) Installing gettext (0.20.2-r0)
> (29/95) Installing gettext-dev (0.20.2-r0)
> (30/95) Installing libxml2-utils (2.9.10-r5)
> (31/95) Installing libgpg-error (1.37-r0)
> (32/95) Installing libgcrypt (1.8.5-r0)
> (33/95) Installing libxslt (1.1.34-r0)
> (34/95) Installing docbook-xml (4.5-r6)
> Executing docbook-xml-4.5-r6.post-install
> (35/95) Installing docbook-xsl (1.79.2-r2)
> Executing docbook-xsl-1.79.2-r2.post-install
> (36/95) Installing linux-headers (5.4.5-r1)
> (37/95) Installing pkgconf (1.7.2-r0)
> (38/95) Installing libffi-dev (3.3-r2)
> (39/95) Installing libpcre16 (8.44-r0)
> (40/95) Installing libpcre32 (8.44-r0)
> (41/95) Installing libpcrecpp (8.44-r0)
> (42/95) Installing pcre-dev (8.44-r0)
> (43/95) Installing blkid (2.35.2-r0)
> (44/95) Installing libcap-ng (0.7.10-r1)
> (45/95) Installing setpriv (2.35.2-r0)
> (46/95) Installing libsmartcols (2.35.2-r0)
> (47/95) Installing findmnt (2.35.2-r0)
> (48/95) Installing mcookie (2.35.2-r0)
> (49/95) Installing hexdump (2.35.2-r0)
> (50/95) Installing lsblk (2.35.2-r0)
> (51/95) Installing libuuid (2.35.2-r0)
> (52/95) Installing libfdisk (2.35.2-r0)
> (53/95) Installing sfdisk (2.35.2-r0)
> (54/95) Installing cfdisk (2.35.2-r0)
> (55/95) Installing util-linux (2.35.2-r0)
> (56/95) Installing util-linux-dev (2.35.2-r0)
> (57/95) Installing zlib-dev (1.2.11-r3)
> (58/95) Installing glib-dev (2.64.6-r0)
> (59/95) Installing enchant2-dev (2.2.8-r2)
> (60/95) Installing unixodbc (2.3.7-r2)
> (61/95) Installing freetds (1.1.40-r0)
> (62/95) Installing freetds-dev (1.1.40-r0)
> (63/95) Installing gmp (6.2.0-r0)
> (64/95) Installing libgmpxx (6.2.0-r0)
> (65/95) Installing gmp-dev (6.2.0-r0)
> (66/95) Installing icu (67.1-r0)
> (67/95) Installing icu-dev (67.1-r0)
> (68/95) Installing c-client (2007f-r11)
> (69/95) Installing imap-dev (2007f-r11)
> (70/95) Installing libpng (1.6.37-r1)
> (71/95) Installing libpng-dev (1.6.37-r1)
> (72/95) Installing xz-dev (5.2.5-r0)
> (73/95) Installing libxml2-dev (2.9.10-r5)
> (74/95) Installing libxslt-dev (1.1.34-r0)
> (75/95) Installing libzip (1.6.1-r1)
> (76/95) Installing libzip-dev (1.6.1-r1)
> (77/95) Installing openssl-dev (1.1.1i-r0)
> (78/95) Installing net-snmp-libs (5.8-r3)
> (79/95) Installing net-snmp-agent-libs (5.8-r3)
> (80/95) Installing net-snmp-dev (5.8-r3)
> ERROR: Failed to create usr/lib/libnetsnmpmibs.a: No error information
> ERROR: net-snmp-dev-5.8-r3: BAD signature
> (81/95) Installing db (5.3.28-r1)
> (82/95) Installing libsasl (2.1.27-r6)
> (83/95) Installing cyrus-sasl-dev (2.1.27-r6)
> (84/95) Installing libldap (2.4.50-r1)
> (85/95) Installing libldapcpp (2.4.50-r1)
> (86/95) Installing openldap-dev (2.4.50-r1)
> (87/95) Installing llvm10-libs (10.0.0-r2)
> ERROR: Failed to create usr/lib/libLLVM-10.so: No error information
> ERROR: llvm10-libs-10.0.0-r2: BAD signature
> (88/95) Installing clang-libs (10.0.0-r2)
> ERROR: Failed to create usr/lib/libclang-cpp.so.10: No error information
> ERROR: clang-libs-10.0.0-r2: BAD signature
> (89/95) Installing clang (10.0.0-r2)
> ERROR: Failed to create usr/bin/c-index-test: No error information
> ERROR: clang-10.0.0-r2: BAD signature
> (90/95) Installing llvm10 (10.0.0-r2)
> (91/95) Installing libpq (12.5-r0)
> (92/95) Installing postgresql-libs (12.5-r0)
> (93/95) Installing postgresql-dev (12.5-r0)
> (94/95) Installing tidyhtml-libs (5.6.0-r0)
> (95/95) Installing tidyhtml-dev (5.6.0-r0)
> Executing busybox-1.31.1-r19.trigger
> Executing glib-2.64.6-r0.trigger
> No schema files found: doing nothing.
> 6 errors; 166 MiB in 120 packages
> ERROR: Service '8-0-0-fpm-ext' failed to build : The command '/bin/sh -c apk add --no-cache --update bzip2-dev enchant2-dev libpng-dev gmp-dev imap-dev icu-dev openldap-dev freetds-dev postgresql-dev aspell-dev net-snmp-dev libxml2-dev tidyhtml-dev libxslt-dev libzip-dev' returned a non-zero code: 6
> 
> Regards,
> Mohammad

I’ve deleted my own docker image and build it from scratch again. And I don’t have this problem BAD signature problem.

I’ve tested this on a 
- PopOS desktop
- VPS 1 Core, 1024 MB memory.

If you still have problems, maybe you can use this docker image instead: harianto/8-0-0-fpm-ext
Maybe you’ve got something that blocks signature checking? Or remove some libraries by commenting out some lines.
